### ISSUE TITLE
Wiki - How to create request

### ISSUE THREAD

**Issue by Kurukshetran** [adelbs/ISO8583#25]

**Comment by adelbs** [comment]
Sorry about the late response.... I'll create the wiki soon.

**Comment by adelbs** [comment]
To create a request:

1) You need to configure the ISO8583 message structure at the ISO Configure tab. You can open a saved configuration instead using the "open" button at the top-right.

2) In the ISO8583 Request tab, connect to a socket server. At the "Request" tab you can configure what values you want to send at each bit.

3) After sending the message, at the "Reponse" tab, when you click the "Next Payload" button, it checks if there is a response to your request.

If you do not have a socket server, you can create one at the "ISO8583-Server" tab.

Let me know if it helps.

**Comment by tiagoms1** [comment]
Sample of isoconfig file and payload tests can be found in: https://github.com/adelbs/DevTest-ISO8583/tree/master/resources
