### ISSUE TITLE
Manifest problem

### ISSUE THREAD

**Issue by bastet77** [adelbs/ISO8583#29]
Hi,

Fails to run following Manifest changes.

c:\iso8583\ISO8583-master\target>java -jar Adelbs-ISO8583-1.1.2.jar
no main manifest attribute, in Adelbs-ISO8583-1.1.2.jar

c:\iso8583\ISO8583-master\target>

c:\iso8583\ISO8583-master\target>mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T19:41:4
7+01:00)
Maven home: C:\apache-maven\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\J
ava\jdk1.8.0_201\jre
Default locale: en_GB, platform encoding: Cp1252
OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "windows"

**Comment by TorgeirFladby** [comment]
Were you able to resolve this? I have the same issue when compiling on Linux. Any way one could manually submit the path for Main.class when running the .jar file?

**Comment by tiagoms1** [comment]
To execute the component via java command line here is the sample: java -cp <jar file name>.jar org.adelbs.iso8583.Main
