### ISSUE TITLE
NullPointerException 

### ISSUE THREAD

**Issue by bastet77** [adelbs/ISO8583#30]
I recompiled latest version 1.1.2 but still get a problem.

Many thanks

Ed Holt

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.466 s
[INFO] Finished at: 2019-06-01T16:35:41+01:00
[INFO] ------------------------------------------------------------------------

C:\ISO8583\ISO8583-master\ISO8583-master>cd target

C:\ISO8583\ISO8583-master\ISO8583-master\target>java -cp ./Adelbs-ISO8583-1.1.2.jar org.adelbs.iso8583.Main
Exception in thread "main" java.lang.NullPointerException
        at sun.awt.SunToolkit.getImageFromHash(Unknown Source)
        at sun.awt.SunToolkit.getImage(Unknown Source)
        at org.adelbs.iso8583.Main.<init>(Main.java:50)
        at org.adelbs.iso8583.Main.main(Main.java:25)

C:\ISO8583\ISO8583-master\ISO8583-master\target>

**Comment by ghost** [comment]
Hi,
I fixed this problem and now the Panel is opening correctly within Netbeans. Had to setup the correct directory structure.

Thanks 

Ed
